# Build stage
FROM node:18-alpine as build

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy rest of code and build React app
COPY . .
RUN npm run build

# Production stage with nginx
FROM nginx:stable-alpine

# Copy built React app to nginx folder
COPY --from=build /app/build /usr/share/nginx/html

# Expose nginx port
EXPOSE 80
