services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/expense-tracker
    depends_on:
      - mongo

  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
